# Generated by Django 5.2.3 on 2026-02-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('CRIT', 'Critical')], db_index=True, max_length=5)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.SmallIntegerField(db_index=True)),
                ('execution_time_ms', models.IntegerField()),
                ('client_ip_hash', models.CharField(blank=True, max_length=16, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_logs',
                'indexes': [models.Index(fields=['-timestamp', 'level'], name='idx_log_ts_level'), models.Index(fields=['endpoint', '-timestamp'], name='idx_log_endpoint'), models.Index(fields=['status_code', '-timestamp'], name='idx_log_status')],
            },
        ),
    ]
