# Generated by Django 5.2.3 on 2026-02-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_fix_token_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='request_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
