# Generated by Django 5.2.3 on 2026-02-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_apilog_request_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('endpoint_pattern', models.CharField(help_text="Pattern regex de l'endpoint", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_view_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserViewPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_permissions', to=settings.AUTH_USER_MODEL)),
                ('view_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.viewpermission')),
            ],
            options={
                'db_table': 'api_user_view_permissions',
                'unique_together': {('user', 'view_permission')},
            },
        ),
    ]
