"""
Django settings for API_BIA project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))

def env_list(name: str, default: list[str] | None = None) -> list[str]:
    val = os.environ.get(name)
    if not val:
        return default or []
    # comma-separated: "a,b,c"
    return [x.strip() for x in val.split(",") if x.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("API_DB_ENGINE", "False")

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])
# CSRF_TRUSTED_ORIGINS = [
    # env_list("CSRF_TRUSTED_ORIGINS", default=["localhost", "127.0.0.1"])
# ]
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {},
    'USE_SESSION_AUTH': False,  # Désactive l'authentification par session
    'LOGIN_URL': None,  # Désactive le bouton de login
    'LOGOUT_URL': None,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': "Format : `Bearer <access_token>` (obtenu via `/api/token/` ou `/api/token/refresh/`)"
        }
    },
    'PERSIST_AUTH': True,
    'REFETCH_SCHEMA_WITH_AUTH': True,
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',
    'DEFAULT_INFO': 'API_BIA.urls.api_info',  # Pointe vers une fonction qui retourne les infos de l'API
    'VALIDATOR_URL': None,
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,

}
#HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# SECURE_SSL_REDIRECT = False
# SESSION_COOKIE_SECURE = True  # Cookies de session uniquement en HTTPS
# CSRF_COOKIE_SECURE = True     # Cookies CSRF uniquement en HTTPS
# SECURE_HSTS_SECONDS = 31536000  # Active HSTS (HTTP Strict Transport Security)
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'API',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'drf_yasg',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'API.middleware.logging_middleware.APILoggingMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'API_BIA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'API_BIA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("API_DB_ENGINE", "mssql"),
        "HOST": os.environ.get("API_DB_HOST", ""),
        "NAME": os.environ.get("API_DB_NAME", ""),
        "USER": os.environ.get("API_DB_USER", ""),
        "PASSWORD": os.environ.get("API_DB_PASSWORD", ""),
        "PORT": os.environ.get("API_DB_PORT", "1433"),
        "OPTIONS": {
            "driver": os.environ.get("API_DB_DRIVER", "ODBC Driver 17 for SQL Server"),
        },
    },
    "dbo": {
        "ENGINE": os.environ.get("DBO_DB_ENGINE", "mssql"),
        "HOST": os.environ.get("DBO_DB_HOST", ""),
        "NAME": os.environ.get("DBO_DB_NAME", ""),
        "USER": os.environ.get("DBO_DB_USER", ""),
        "PASSWORD": os.environ.get("DBO_DB_PASSWORD", ""),
        "PORT": os.environ.get("DBO_DB_PORT", "1433"),
        "OPTIONS": {
            "driver": os.environ.get("DBO_DB_DRIVER", "ODBC Driver 17 for SQL Server"),
        },
    },
    "lkr": {
        "ENGINE": os.environ.get("LKR_DB_ENGINE", "mssql"),
        "HOST": os.environ.get("LKR_DB_HOST", ""),
        "NAME": os.environ.get("LKR_DB_NAME", ""),
        "USER": os.environ.get("LKR_DB_USER", ""),
        "PASSWORD": os.environ.get("LKR_DB_PASSWORD", ""),
        "PORT": os.environ.get("LKR_DB_PORT", "1433"),
        "OPTIONS": {
            "driver": os.environ.get("LKR_DB_DRIVER", "ODBC Driver 17 for SQL Server"),
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=2),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'